// Generated by `zfa package create` (spec 025) — the package test harness.
import 'package:test/test.dart';
import 'package:zuraffa/zuraffa.dart';
import 'package:zuraffa_minio/zuraffa_minio.dart';

void main() {
  test('package exposes a registrable module', () {
    final module = ZuraffaMinioPackageModule();
    expect(module.pluginId, 'zuraffa_minio');
    expect(module.routes, isEmpty);
  });

  test('package registrar runs cleanly on a fresh container', () {
    // A module-only package registers nothing but must not throw.
    registerZuraffaMinioPackage(ZuraffaDIContainer());
  });
}
