// Generated by `zfa package create` (spec 025, FR-004).
//
// The package registrar is the standalone registration unit a consuming
// app merges into its dependency container via the package module —
// registration is strictly import-scoped (FR-005). `zfa make <Entity>
// ... --di` regenerates this file with every contributed registration.
import 'package:zuraffa/zuraffa.dart';

/// Registers every datasource/repository/usecase contributed by the
/// `zuraffa_minio` package into the consuming app's [di] container.
///
/// Until entities are generated this registers nothing (a module-only
/// package is valid — spec edge case).
void registerZuraffaMinioPackage(ZuraffaDIContainer di) {
  // Registrations land here as `zfa make ... di` generates architecture
  // (one registrar per package, multi-entity single pass — FR-012).
}
