// Generated by `zfa package create` (spec 025, FR-006).
import 'package:zuraffa/zuraffa.dart';

import '../di/zuraffa_minio_package_registrar.dart';

/// Runtime module of the `zuraffa_minio` package.
///
/// A consuming app activates this module to register the package's
/// contributed datasources / repositories / usecases into the app's DI
/// container (zero manual registration, FR-005) and to participate in the
/// engine lifecycle: registerDependencies -> onInit -> onReady -> onDispose.
class ZuraffaMinioPackageModule extends PackageModule {
  /// The zuraffa constraint this package was generated against (FR-015).
  /// `ZuraffaEngine.registerPackage` validates it against the running
  /// version and rejects major mismatches with a clear error.
  @override
  String get zuraffaSdkConstraint => '^6.2.3';

  @override
  String get pluginId => 'zuraffa_minio';

  @override
  void registerDependencies(ZuraffaDIContainer di) {
    registerZuraffaMinioPackage(di);
  }

  @override
  Map<String, ZuraffaRouteHandler> get routes => const {};

  /// Runs after every registered module finished `onInit`.
  @override
  Future<void> onReady(ZuraffaDIContainer di) async {}

  /// Runs in reverse registration order on engine shutdown.
  @override
  Future<void> onDispose(ZuraffaDIContainer di) async {}
}
